'use client';

export default function ExportButton({ results }) {
  const handleExport = () => {
    // Build a clean text report
    const lines = [];
    lines.push('═══════════════════════════════════════════════');
    lines.push('  KASPAROO AI READINESS REPORT');
    lines.push('═══════════════════════════════════════════════');
    lines.push('');
    lines.push(`Store: ${results.storeName}`);
    lines.push(`URL: ${results.storeUrl}`);
    lines.push(`Category: ${results.category?.primary || 'General'}`);
    lines.push(`Products: ${results.productCount} | Collections: ${results.collectionCount}`);
    lines.push(`Scanned: ${new Date(results.scannedAt).toLocaleString()}`);
    lines.push('');
    lines.push(`OVERALL SCORE: ${results.overallScore}/100`);
    lines.push('─────────────────────────────────────────────');
    lines.push('');

    // Dimensions
    lines.push('DIMENSION SCORES');
    lines.push('─────────────────────────────────────────────');
    Object.values(results.dimensions).forEach((dim) => {
      const bar = '█'.repeat(Math.round(dim.score / 5)) + '░'.repeat(20 - Math.round(dim.score / 5));
      lines.push(`  ${dim.label.padEnd(28)} ${bar} ${dim.score}/100 (${dim.weight}%)`);
    });
    lines.push('');

    // Issues
    lines.push(`ACTION PLAN (${results.issues.length} improvements)`);
    lines.push('─────────────────────────────────────────────');
    results.issues.forEach((issue, i) => {
      lines.push(`  #${i + 1} [${issue.severity.toUpperCase()}] ${issue.area}`);
      lines.push(`     ${issue.message}`);
      lines.push(`     Fix: ${issue.fix}`);
      lines.push(`     Impact: +${issue.impact}pts | Effort: ${issue.effort}`);
      lines.push('');
    });

    // Top products
    lines.push('TOP 10 PRODUCT SCORES');
    lines.push('─────────────────────────────────────────────');
    results.productSummary.slice(0, 10).forEach((p) => {
      lines.push(`  ${p.title.slice(0, 40).padEnd(42)} Score: ${p.score}/100`);
    });
    lines.push('');
    lines.push('─────────────────────────────────────────────');
    lines.push('Generated by Kasparoo AI Readiness Scanner');
    lines.push('Built for Kasparro Internship Challenge — Track 5');

    const text = lines.join('\n');
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `kasparoo-report-${results.storeName.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="export-buttons">
      <button className="btn-export" onClick={handleExport} title="Download as text file">
        📄 Download Report
      </button>
      <button className="btn-export btn-export-secondary" onClick={handlePrint} title="Print or save as PDF">
        🖨️ Print / PDF
      </button>
    </div>
  );
}
